// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.aidokay.proto.order

object OrderProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      order.CreateOrderRequest,
      order.Item,
      order.CreateOrderResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgtvcmRlci5wcm90byKSAQoSQ3JlYXRlT3JkZXJSZXF1ZXN0EiQKB3VzZXJfaWQYASABKANCC+I/CBIGdXNlcklkUgZ1c2VyS
  WQSJAoEaXRlbRgCIAMoCzIFLkl0ZW1CCeI/BhIEaXRlbVIEaXRlbRIwCgt0b3RhbF9wcmljZRgDIAEoAkIP4j8MEgp0b3RhbFBya
  WNlUgp0b3RhbFByaWNlIiUKBEl0ZW0SHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lIj4KE0NyZWF0ZU9yZGVyUmVzcG9uc
  2USJwoIb3JkZXJfaWQYASABKANCDOI/CRIHb3JkZXJJZFIHb3JkZXJJZDI+CgVPcmRlchI1CgZjcmVhdGUSEy5DcmVhdGVPcmRlc
  lJlcXVlc3QaFC5DcmVhdGVPcmRlclJlc3BvbnNlIgBCG1oZR2l0aHViL2phbWVzd2FuZy9nby9vcmRlcmIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}